"""empty message

Revision ID: 02e7c8c58e35
Revises: 3c659a7fcff2
Create Date: 2018-03-11 00:00:50.826478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e7c8c58e35'
down_revision = '3c659a7fcff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receive', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('buy_time', sa.DateTime(), nullable=True),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('freight', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pay_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('integral', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('evaluate_buyers', sa.Boolean(), nullable=True),
    sa.Column('evaluate_buyers_time', sa.DateTime(), nullable=True),
    sa.Column('evaluate_buyers_note', sa.UnicodeText(), nullable=True),
    sa.Column('evaluate_seller', sa.Boolean(), nullable=True),
    sa.Column('evaluate_seller_time', sa.DateTime(), nullable=True),
    sa.Column('evaluate_seller_note', sa.UnicodeText(), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receive'], ['user_address.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.Column('goods_allocation_id', sa.Integer(), nullable=True),
    sa.Column('UserOrder_id', sa.Integer(), nullable=True),
    sa.Column('residue_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserOrder_id'], ['user_order.id'], ),
    sa.ForeignKeyConstraint(['goods_allocation_id'], ['goods_allocation.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['goodsed.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    op.drop_table('receipts')
    # ### end Alembic commands ###
