"""empty message

Revision ID: 0307fcac75c6
Revises: cf3780392f94
Create Date: 2018-04-30 11:28:47.897456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0307fcac75c6'
down_revision = 'cf3780392f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('goods_allocation_name', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('goods_title', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('main_photo', sa.String(length=200), nullable=True))
    op.add_column('sales', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('special_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_constraint('sales_ibfk_1', 'sales', type_='foreignkey')
    op.drop_constraint('sales_ibfk_2', 'sales', type_='foreignkey')
    op.drop_column('sales', 'goods_id')
    op.drop_column('sales', 'goods_allocation_id')
    op.add_column('stocks', sa.Column('goods_allocation_name', sa.String(length=100), nullable=True))
    op.add_column('stocks', sa.Column('goods_title', sa.String(length=100), nullable=True))
    op.add_column('stocks', sa.Column('main_photo', sa.String(length=200), nullable=True))
    op.add_column('stocks', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stocks', sa.Column('special_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_constraint('stocks_ibfk_3', 'stocks', type_='foreignkey')
    op.drop_constraint('stocks_ibfk_2', 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'goods_id')
    op.drop_column('stocks', 'goods_allocation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('goods_allocation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('stocks', sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('stocks_ibfk_2', 'stocks', 'goods_allocation', ['goods_allocation_id'], ['id'])
    op.create_foreign_key('stocks_ibfk_3', 'stocks', 'goodsed', ['goods_id'], ['id'])
    op.drop_column('stocks', 'special_price')
    op.drop_column('stocks', 'original_price')
    op.drop_column('stocks', 'main_photo')
    op.drop_column('stocks', 'goods_title')
    op.drop_column('stocks', 'goods_allocation_name')
    op.add_column('sales', sa.Column('goods_allocation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('sales_ibfk_2', 'sales', 'goodsed', ['goods_id'], ['id'])
    op.create_foreign_key('sales_ibfk_1', 'sales', 'goods_allocation', ['goods_allocation_id'], ['id'])
    op.drop_column('sales', 'special_price')
    op.drop_column('sales', 'original_price')
    op.drop_column('sales', 'main_photo')
    op.drop_column('sales', 'goods_title')
    op.drop_column('sales', 'goods_allocation_name')
    # ### end Alembic commands ###
