"""empty message

Revision ID: 0345d7541a86
Revises: bae3f9a94877
Create Date: 2018-03-06 00:46:09.957455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0345d7541a86'
down_revision = 'bae3f9a94877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ico', sa.String(length=100), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorys')
    # ### end Alembic commands ###
