"""empty message

Revision ID: 0c0a215fe420
Revises: 24c90d243db8
Create Date: 2018-03-18 02:16:39.185071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c0a215fe420'
down_revision = '24c90d243db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'stocks_ibfk_4', 'stocks', type_='foreignkey')
    op.create_foreign_key(None, 'stocks', 'users', ['user_id'], ['id'])
    op.drop_column('stocks', 'seller_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('seller_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.create_foreign_key(u'stocks_ibfk_4', 'stocks', 'sellers', ['seller_id'], ['id'])
    op.drop_column('stocks', 'user_id')
    # ### end Alembic commands ###
