"""empty message

Revision ID: 146e1c851239
Revises: 668946f2e7fc
Create Date: 2018-03-10 23:06:08.400486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146e1c851239'
down_revision = '668946f2e7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'level')
    # ### end Alembic commands ###
