"""empty message

Revision ID: 1f7d03325768
Revises: 7bfed151d1ce
Create Date: 2018-03-14 03:49:30.649676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7d03325768'
down_revision = '7bfed151d1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('sellers_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouses', 'sellers', ['sellers_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'sellers_id')
    # ### end Alembic commands ###
