"""empty message

Revision ID: 35571e743572
Revises: 88374b5ade1d
Create Date: 2018-03-24 16:14:19.592954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35571e743572'
down_revision = '88374b5ade1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('goods_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'inventory_ibfk_1', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'goodsed', ['goods_id'], ['id'])
    op.drop_column('inventory', 'good_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('good_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(u'inventory_ibfk_1', 'inventory', 'goodsed', ['good_id'], ['id'])
    op.drop_column('inventory', 'goods_id')
    # ### end Alembic commands ###
