"""empty message

Revision ID: 3a6a589ea412
Revises: e4a3f10ca070
Create Date: 2018-04-11 14:54:58.572638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6a589ea412'
down_revision = 'e4a3f10ca070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('goods_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_order', 'goods_number')
    # ### end Alembic commands ###
