"""empty message

Revision ID: 3c659a7fcff2
Revises: fae316560fb4
Create Date: 2018-03-10 23:39:27.175171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c659a7fcff2'
down_revision = 'fae316560fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('residue_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'residue_count')
    # ### end Alembic commands ###
