"""empty message

Revision ID: 4e15ac65dd94
Revises: 220cd2617379
Create Date: 2018-03-17 02:11:35.004454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e15ac65dd94'
down_revision = '220cd2617379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'user_id')
    # ### end Alembic commands ###
