"""empty message

Revision ID: 514d56b71c6e
Revises: 6a1efdcbaf4c
Create Date: 2018-04-20 14:55:55.783231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '514d56b71c6e'
down_revision = '6a1efdcbaf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_products', sa.Column('main_photo', sa.String(length=200), nullable=True))
    op.add_column('base_products', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('base_products', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_products', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('base_products', 'title')
    op.drop_column('base_products', 'main_photo')
    # ### end Alembic commands ###
