"""empty message

Revision ID: 58d24e3f5f26
Revises: c7c7f561722c
Create Date: 2018-04-14 04:28:17.187972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d24e3f5f26'
down_revision = 'c7c7f561722c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('is_pay', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_order', 'is_pay')
    # ### end Alembic commands ###
