"""empty message

Revision ID: 5909e24c183f
Revises: 63871105adb3
Create Date: 2018-03-18 14:33:25.822606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5909e24c183f'
down_revision = '63871105adb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'receipts_ibfk_2', 'receipts', type_='foreignkey')
    op.create_foreign_key(None, 'receipts', 'users', ['user_id'], ['id'])
    op.drop_column('receipts', 'seller_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('seller_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.create_foreign_key(u'receipts_ibfk_2', 'receipts', 'sellers', ['seller_id'], ['id'])
    op.drop_column('receipts', 'user_id')
    # ### end Alembic commands ###
