"""empty message

Revision ID: 5f94c45b3c47
Revises: 25f959c966d8
Create Date: 2018-04-25 14:15:45.660232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f94c45b3c47'
down_revision = '25f959c966d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quantity_check', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('quantity_check_goods', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('quantity_check_goods', sa.Column('submit_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quantity_check_goods', 'submit_change')
    op.drop_column('quantity_check_goods', 'location')
    op.drop_column('quantity_check', 'title')
    # ### end Alembic commands ###
