"""empty message

Revision ID: 63871105adb3
Revises: 0c0a215fe420
Create Date: 2018-03-18 14:10:08.468790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63871105adb3'
down_revision = '0c0a215fe420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('stock_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'stock_count')
    # ### end Alembic commands ###
