"""empty message

Revision ID: 668946f2e7fc
Revises: 454cab62186d
Create Date: 2018-03-10 22:56:10.136000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668946f2e7fc'
down_revision = '454cab62186d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('max_goods_count', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('max_goods_location', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('max_order', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('max_price', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('max_warehouse', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'max_warehouse')
    op.drop_column('sellers', 'max_price')
    op.drop_column('sellers', 'max_order')
    op.drop_column('sellers', 'max_goods_location')
    op.drop_column('sellers', 'max_goods_count')
    # ### end Alembic commands ###
