"""empty message

Revision ID: 66ea073821ac
Revises: 02e7c8c58e35
Create Date: 2018-03-11 00:05:54.040903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66ea073821ac'
down_revision = '02e7c8c58e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('pay_type', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('supplier', sa.String(length=100), nullable=True))
    op.drop_constraint(u'receipts_ibfk_1', 'receipts', type_='foreignkey')
    op.drop_constraint(u'receipts_ibfk_3', 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'evaluate_seller_note')
    op.drop_column('receipts', 'evaluate_buyers_note')
    op.drop_column('receipts', 'user_id')
    op.drop_column('receipts', 'evaluate_seller_time')
    op.drop_column('receipts', 'receive')
    op.drop_column('receipts', 'integral')
    op.drop_column('receipts', 'evaluate_buyers_time')
    op.drop_column('receipts', 'evaluate_seller')
    op.drop_column('receipts', 'evaluate_buyers')
    op.add_column('stocks', sa.Column('receipts_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'stocks_ibfk_1', 'stocks', type_='foreignkey')
    op.create_foreign_key(None, 'stocks', 'receipts', ['receipts_id'], ['id'])
    op.drop_column('stocks', 'UserOrder_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('UserOrder_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.create_foreign_key(u'stocks_ibfk_1', 'stocks', 'user_order', ['UserOrder_id'], ['id'])
    op.drop_column('stocks', 'receipts_id')
    op.add_column('receipts', sa.Column('evaluate_buyers', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('evaluate_seller', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('evaluate_buyers_time', mysql.DATETIME(), nullable=True))
    op.add_column('receipts', sa.Column('integral', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('receive', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('evaluate_seller_time', mysql.DATETIME(), nullable=True))
    op.add_column('receipts', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('evaluate_buyers_note', mysql.TEXT(), nullable=True))
    op.add_column('receipts', sa.Column('evaluate_seller_note', mysql.TEXT(), nullable=True))
    op.create_foreign_key(u'receipts_ibfk_3', 'receipts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(u'receipts_ibfk_1', 'receipts', 'user_address', ['receive'], ['id'])
    op.drop_column('receipts', 'supplier')
    op.drop_column('receipts', 'pay_type')
    # ### end Alembic commands ###
