"""empty message

Revision ID: 6a1efdcbaf4c
Revises: 58d24e3f5f26
Create Date: 2018-04-18 12:25:43.450695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1efdcbaf4c'
down_revision = '58d24e3f5f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goodsed', sa.Column('main_photo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goodsed', 'main_photo')
    # ### end Alembic commands ###
