"""empty message

Revision ID: 6c8d67ab94b3
Revises: bf732133e4ed
Create Date: 2018-03-19 01:17:45.511357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c8d67ab94b3'
down_revision = 'bf732133e4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'follows_ibfk_2', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'sellers', ['seller_id'], ['id'])
    op.drop_column('follows', 'sellers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('sellers_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(u'follows_ibfk_2', 'follows', 'sellers', ['sellers_id'], ['id'])
    op.drop_column('follows', 'seller_id')
    # ### end Alembic commands ###
