"""empty message

Revision ID: 6e761bb2338b
Revises: 146e1c851239
Create Date: 2018-03-10 23:30:03.890808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e761bb2338b'
down_revision = '146e1c851239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wechat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wechat_id', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
