"""empty message

Revision ID: 7baf280f330a
Revises: 1f7d03325768
Create Date: 2018-03-14 16:08:45.875371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baf280f330a'
down_revision = '1f7d03325768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_allocation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goods_allocation', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods_allocation', type_='foreignkey')
    op.drop_column('goods_allocation', 'user_id')
    # ### end Alembic commands ###
