"""empty message

Revision ID: 7bfed151d1ce
Revises: 997156e954e5
Create Date: 2018-03-14 03:29:01.464241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bfed151d1ce'
down_revision = '997156e954e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_allocation', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('goods_allocation', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_allocation', sa.Column('title', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('goods_allocation', 'name')
    # ### end Alembic commands ###
