"""empty message

Revision ID: 85884c285596
Revises: c1208dcdc04e
Create Date: 2018-03-05 23:30:57.437010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85884c285596'
down_revision = 'c1208dcdc04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_address', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_address', 'user_address', ['user_id'], ['id'])
    op.drop_constraint(u'users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_1', 'users', 'user_address', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_address', type_='foreignkey')
    op.drop_column('user_address', 'user_id')
    # ### end Alembic commands ###
