"""empty message

Revision ID: 88374b5ade1d
Revises: d653299aaab4
Create Date: 2018-03-21 21:24:54.210767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88374b5ade1d'
down_revision = 'd653299aaab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sellers', sa.Column('max_price_no_freight', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'max_price_no_freight')
    op.drop_column('sellers', 'freight')
    # ### end Alembic commands ###
