"""empty message

Revision ID: 8d3d9d77ac82
Revises: 35571e743572
Create Date: 2018-03-25 14:58:42.870122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d3d9d77ac82'
down_revision = '35571e743572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_address', sa.Column('name', sa.String(length=20), nullable=True))
    op.drop_column('user_address', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_address', sa.Column('username', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user_address', 'name')
    # ### end Alembic commands ###
