"""empty message

Revision ID: 997156e954e5
Revises: 57f78d2d10a3
Create Date: 2018-03-13 22:45:25.196488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997156e954e5'
down_revision = '57f78d2d10a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goodsed', sa.Column('ean', sa.String(length=50), nullable=True))
    op.add_column('goodsed', sa.Column('unit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goodsed', 'unit')
    op.drop_column('goodsed', 'ean')
    # ### end Alembic commands ###
