"""empty message

Revision ID: bae3f9a94877
Revises: debc26366e1c
Create Date: 2018-03-06 00:08:13.972610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae3f9a94877'
down_revision = 'debc26366e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('context', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_versions')
    # ### end Alembic commands ###
