"""empty message

Revision ID: c1208dcdc04e
Revises: 00f8a497d138
Create Date: 2018-03-05 23:29:44.623460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1208dcdc04e'
down_revision = '00f8a497d138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('address_map', sa.String(length=100), nullable=True))
    op.add_column(u'users', sa.Column('last_time', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column(u'users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_index('email', table_name='users')
    op.create_foreign_key(None, 'users', 'user_address', ['user_id'], ['id'])
    op.drop_column(u'users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('email', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column(u'users', 'user_id')
    op.drop_column(u'users', 'phone')
    op.drop_column(u'users', 'last_time')
    op.drop_column(u'users', 'address_map')
    op.drop_table('user_address')
    # ### end Alembic commands ###
