"""empty message

Revision ID: c336d396f45d
Revises: 8d3d9d77ac82
Create Date: 2018-03-26 01:57:45.288240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c336d396f45d'
down_revision = '8d3d9d77ac82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'count')
    # ### end Alembic commands ###
