"""empty message

Revision ID: c6575d31ca3f
Revises: 29e162f0903a
Create Date: 2018-06-01 23:34:52.191647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6575d31ca3f'
down_revision = '29e162f0903a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.drop_column('sellers', 'email')
    # ### end Alembic commands ###
