"""empty message

Revision ID: cf3780392f94
Revises: 5f94c45b3c47
Create Date: 2018-04-25 14:50:06.975691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf3780392f94'
down_revision = '5f94c45b3c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quantity_check_goods', sa.Column('goods_name', sa.String(length=50), nullable=True))
    op.add_column('quantity_check_goods', sa.Column('inventory_id', sa.Integer(), nullable=True))
    op.drop_constraint('quantity_check_goods_ibfk_1', 'quantity_check_goods', type_='foreignkey')
    op.drop_column('quantity_check_goods', 'goods_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quantity_check_goods', sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('quantity_check_goods_ibfk_1', 'quantity_check_goods', 'goodsed', ['goods_id'], ['id'])
    op.drop_column('quantity_check_goods', 'inventory_id')
    op.drop_column('quantity_check_goods', 'goods_name')
    # ### end Alembic commands ###
