"""empty message

Revision ID: d04bc25129d0
Revises: a15890676b12
Create Date: 2018-03-19 01:11:58.750322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04bc25129d0'
down_revision = 'a15890676b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'follows_ibfk_1', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(u'follows_ibfk_1', 'follows', 'sellers', ['user_id'], ['id'])
    op.drop_column('follows', 'seller_id')
    # ### end Alembic commands ###
