"""empty message

Revision ID: debc26366e1c
Revises: 85884c285596
Create Date: 2018-03-05 23:57:41.652107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debc26366e1c'
down_revision = '85884c285596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('special_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('note', sa.UnicodeText(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('attach_key', sa.String(length=200), nullable=True),
    sa.Column('attach_value', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'user_address_ibfk_1', 'user_address', type_='foreignkey')
    op.create_foreign_key(None, 'user_address', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_address', type_='foreignkey')
    op.create_foreign_key(u'user_address_ibfk_1', 'user_address', 'user_address', ['user_id'], ['id'])
    op.drop_table('base_products')
    # ### end Alembic commands ###
