"""empty message

Revision ID: e4a3f10ca070
Revises: c336d396f45d
Create Date: 2018-04-11 00:53:01.539363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4a3f10ca070'
down_revision = 'c336d396f45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'receipts', ['number'])
    op.add_column('user_order', sa.Column('receive_address', sa.String(length=100), nullable=True))
    op.add_column('user_order', sa.Column('receive_name', sa.String(length=100), nullable=True))
    op.add_column('user_order', sa.Column('receive_phone', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user_order', ['number'])
    op.drop_constraint(u'user_order_ibfk_1', 'user_order', type_='foreignkey')
    op.drop_column('user_order', 'receive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('receive', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'user_order_ibfk_1', 'user_order', 'user_address', ['receive'], ['id'])
    op.drop_constraint(None, 'user_order', type_='unique')
    op.drop_column('user_order', 'receive_phone')
    op.drop_column('user_order', 'receive_name')
    op.drop_column('user_order', 'receive_address')
    op.drop_constraint(None, 'receipts', type_='unique')
    # ### end Alembic commands ###
