"""empty message

Revision ID: e955c3e108e9
Revises: 247386fceb79
Create Date: 2018-03-06 01:06:41.738137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e955c3e108e9'
down_revision = '247386fceb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receive', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('buy_time', sa.DateTime(), nullable=True),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('freight', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pay_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('integral', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('evaluate_buyers', sa.Boolean(), nullable=True),
    sa.Column('evaluate_buyers_time', sa.DateTime(), nullable=True),
    sa.Column('evaluate_buyers_note', sa.UnicodeText(), nullable=True),
    sa.Column('evaluate_seller', sa.Boolean(), nullable=True),
    sa.Column('evaluate_seller_time', sa.DateTime(), nullable=True),
    sa.Column('evaluate_seller_note', sa.UnicodeText(), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receive'], ['user_address.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'sellers', sa.Column('contact', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'sellers', 'contact')
    op.drop_table('user_order')
    # ### end Alembic commands ###
