"""empty message

Revision ID: eac9f5a95842
Revises: 393756f037a1
Create Date: 2018-03-06 00:49:07.770011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac9f5a95842'
down_revision = '393756f037a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goodsed', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goodsed', 'count')
    # ### end Alembic commands ###
