"""empty message

Revision ID: ee397d9ef52e
Revises: e955c3e108e9
Create Date: 2018-03-06 15:19:07.513621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee397d9ef52e'
down_revision = 'e955c3e108e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellers_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('visitor', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.Column('goods_allocation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goods_allocation_id'], ['goods_allocation.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['goodsed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'banners', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column(u'goodsed', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'goodsed', 'created_at')
    op.drop_column(u'banners', 'created_at')
    op.drop_table('sales')
    op.drop_table('sellers_info')
    op.drop_table('goods_allocation')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
