"""empty message

Revision ID: fa67e8808702
Revises: 514d56b71c6e
Create Date: 2018-04-22 23:31:39.497832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa67e8808702'
down_revision = '514d56b71c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_products', sa.Column('ean', sa.String(length=50), nullable=True))
    op.add_column('base_products', sa.Column('unit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_products', 'unit')
    op.drop_column('base_products', 'ean')
    # ### end Alembic commands ###
