"""empty message

Revision ID: fae316560fb4
Revises: 6e761bb2338b
Create Date: 2018-03-10 23:30:22.391069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae316560fb4'
down_revision = '6e761bb2338b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wechat_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wechat_id')
    # ### end Alembic commands ###
