"""empty message

Revision ID: ff4b47ae65dc
Revises: ee397d9ef52e
Create Date: 2018-03-06 15:25:55.163830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4b47ae65dc'
down_revision = 'ee397d9ef52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('UserOrder_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'sellers', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'user_order', ['UserOrder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'seller_id')
    op.drop_column('sales', 'UserOrder_id')
    # ### end Alembic commands ###
